### ISSUE TITLE
Error: `model.get(...).toJS is not a function` if API client puts `Error` value in rejected promises

### ISSUE THREAD

**Issue by hallettj** [uniqueway/redux-crud-store#15]
This problem occurs when selecting a single record, using either `selectRecord` or `select`, if the library user's API client implementation puts `Error` values in rejected promises. Using `Error` values for rejections is a common practice, and is arguably a best practice.

The problem arises because the redux-crud-store reducers attempt to convert error values to Immutable data structures:

``` js
    // reducers.js, line 71
    case FETCH_ONE_ERROR:
      return state.setIn([id.toString(), 'fetchTime'], action.meta.fetchTime)
                  .setIn([id.toString(), 'error'], fromJS(action.payload))  // <-- conversion happens here
                  .setIn([id.toString(), 'record'], null)
```

Selector functions attempt to convert back to a plain Javascript object:

``` js
  // selectors.js, line 129
  if (model.get('error') !== null) {
    return {
      isLoading: false,
      needsFetch: false,
      error: model.get('error').toJS()
    }
  }
```

Immutable's `fromJS` function does not attempt to create immutable versions of `Error` values - it just returns the original value. So the later `.toJS()` invocation fails.

This relates to #9.

**Comment by devvmh** [comment]
So I guess there are a few decisions here
1. Should this library use immutability at all? As long as it works, users of the library probably don't care if we're using immutability under the hood or not. In fact, not using it is probably better for users (again, as long as it works correctly). On the flip side, seamless-immutable and ImmutableJS provide nice methods like setIn.
2. Should errors be a) objects only, which can be used for ImmutableJS; b) any type, which potentially can't be handled by immutable js; c) either a generic object or an Error object, which requires small conditional code; d) _only_ an error object.

For (1), I think in the interests of not doing pointless work, I say let's keep immutability for now, and not switch to seamless-immutable.

For (2), I favour c or d. After reflection, d is probably the best answer because I'd rather use an existing API where possible instead of inventing something library-specific. The more library-specific type definitions, syntaxes, DSLs, APIs, whatever that we can eliminate, the better.

So I'll think about making a pull request that changes the error values to always be JS Error objects. I think it'll be probably 
1. small changes to how the errors are stored using ImmutableJS
2. more changes to the documentation to say how to read the errors
3. figure out if this will constitute a major or minor release. It would be great if it were minor.

**Comment by devvmh** [comment]
Note from the future: see #29

**Comment by hallettj** [comment]
Thanks! Your notes on how to proceed sound good to me.

Since the store operates behind-the-scenes, it seems to me that the main
argument for immutability is better performance due to structural sharing
in case collections become large and are updated frequently.
