### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by patrickgordon** [uniqueway/redux-crud-store#2]
Hi, I came to this repo from Google & Reddit. I was wondering how I could have a discussion with you about this repo.

Specifically, I'm interested in why you built this rather than use redux-orm.

**Comment by devvmh** [comment]
I spent two weeks crying my eyes out looking for a solution that did a few things:

1. Reduce the amount of boilerplate code I had to write
2. Simplify my component logic when selecting/fetching/changing records on the server
3. Manage async logic well, picking up where redux left off
4. Cache requests for performance, and otherwise manage my collections for me like Backbone would.

Most solutions for redux and react, I eventually found, are designed for toy apps, and NOT for a single page application. I was making a single page application.

After making this, I saw redux-crud, and it looks a lot like our old, manual solution that was annoying to work with. I don't want to have 9+ actions for every model.

I hadn't heard of redux-orm until this moment. Honestly, it looks incredible. We've put our SPA on pause for the moment, so it will be a few weeks at least until I work heavily with this repo, but when I do I'm definitely going to check it out. I might even strip a bunch of my code out and use redux-orm as a dependency. The only features this repo has that redux-orm doesn't have is 1) request caching and 2) automatically writes the reducers and selectors for you. What redux-orm does have, and this is huge, is handling of nested models. I had started that on a branch, but I'll probably pull in redux-orm or gaereon/normalizr to finish it when I do.

Thanks a lot for posting about redux-orm! It's hard finding resources for redux single page applications.

What project are you working on?

**Comment by patrickgordon** [comment]
Well I'm a self taught Rails hobbyist. I was working a web app to help me better manage my social / personal relationships - remember birthdays, people's coffees, add notes about them etc.

I wanted to, and was, using React in the view but React + Rails = sprockets madness. The deeper I got the more I saw challenges. There is one good gem currently under way to make this easier (https://github.com/shakacode/react_on_rails) but it is a bit immature for me right now to pick up and use easily. I also realised that I want to eventually build a mobile app and the thought of decoupling a front-end from a back-end of a a more complex app was daunting.

So I decided to stop and re-assess and landed on going down a front-end JS (React, redux, webpack) world and back-end Rails API. FWIW I used this for the front-end as a starting point: https://github.com/davezuko/react-redux-starter-kit

After looking around I think redux-orm is a really brilliant way to pair Rails and everything we love about models and the conventions from that world with Redux/React/front-end JavaScript madness. But, I think you're right - it is missing the two things you mentioned. I think if you were to incorporate the two you could have a very, very useful library. 

Anyway, kudos to you for what you built already and very quickly!!

**Comment by devvmh** [comment]
Please,  please, please, contribute to this project

The codebase is pretty small, so if you were able to use it at all it would be a big deal. Fork it and clone it and then add `"redux-crud-store": "/path/to/redux-crud-store"` to your package.json, and you're set to use it in development.

There are definitely still 1-2 small bugs (I haven't experienced them, I'm just guessing) because this hasn't been used in production long enough. If you could squash those, or even better, integrate redux-orm, that would be pretty great

If you do end up using this at all, definitely post issues and I'll answer as best I can. I know the documentation isn't that great. 

But yeah, the source is also quite small. Reading actionCreators.js and selectors.js should be pretty straightforward. Just stay out of sagas.js if you want your sanity to remain intact

**Comment by patrickgordon** [comment]
Alright, sure I'll use it. Disclaimer though: I'm pretty avg. at JS and haven't really contributed (in a meaningful way) to an open source project before.

Out of curiosity:
1. Why is it called `sagas`? 
2. Isn't garbage collecting like that a code smell?

**Comment by devvmh** [comment]
1. sagas uses redux-saga to manage async. The creator of redux-saga made up that term
2. I don't know about any particular disadvantages of garbage collecting. My main worry was that a user navigating around the app for a long time would end up with a really huge store, which would slow down the reducers and selectors a bunch. It's probably premature optimization. I'd love to read more about the drawbacks of garbage collection in a redux app.

**Comment by devvmh** [comment]
And as for being average - aren't we all! If you write a pull request, I'll review it. I'm sure it will be better than what's already there!
