### ISSUE TITLE
Proposal: Action to reinitialize a store ?

### ISSUE THREAD

**Issue by julienR2** [uniqueway/redux-crud-store#37]
In case we are handling authentication flows, if a user logout and login with other account the "fetch collection" is not called because the request is still cached.

A nice and easy way could be to offer a redux action to reinitialize a model store when logging out. What do you think ?

**Comment by devvmh** [comment]
I think you've got two options here
1. You can send a FETCH or FETCH_ONE action even if needsFetch is false. You just sort of do it manually. It will happily blow away whatever is currently in the store. needsFetch is only there to help components decide when to call a new FETCH (and in fact, you don't really need to call it when it says, since it's kind of arbitrary. You could just call it on page load if you wanted).
2. The clearModelData action might work (only recently added) https://github.com/uniqueway/redux-crud-store/blob/master/docs/API.md#clearmodeldatamodel-string

I'm assuming these will do what you want... but I may be wrong. Let me know if that covers what you're looking for

**Comment by julienR2** [comment]
ClearModelData do perfectly the job 👍 It is what I was looking for !
Thanks for your help !
