### ISSUE TITLE
Way to reinitialize an ApiClient

### ISSUE THREAD

**Issue by Vargentum** [uniqueway/redux-crud-store#45]
I have an SPA that implements token based authentication. I need to reinitialize ApiClient with proper auth header after server gives me a token. 
Are there any ways to do it?

**Comment by devvmh** [comment]
Hi @Vargentum 

If it really is just an auth header, you can pass it in the fetchConfig param. In https://github.com/devvmh/redux-crud-store/blob/master/src/actionCreators.js, you can see how to use this parameter. This will be passed to ApiClient.js, and assuming it's written right it should then include it in all requests. If this doesn't work, it's probably a bug that can be fixed

This might make your action creator code a lot more complicated though

In theory you could also copy-paste the ApiClient.js code into your codebase, modify it to allow reinitializing a constant, and then use that class in your code instead of the default one. I'm having trouble imagining precisely how this would work in real life, but I think it should be possible

Do either of those approaches work?

**Comment by Vargentum** [comment]
@devvmh thanks, your answer leads me to remember that I used this approach to set csrf tokens. 
I propose to reference this issue to #32, because it has an example how to deal with action patching with fetchConfig. Maybe it also should be added to docs.

P.s. Thanks for a cool lib! It does a great work for me.

**Comment by devvmh** [comment]
@Vargentum great to hear, and thanks! If there's any use case that doesn't work for you, please send in a pull request! (or an issue, and maybe I can write the PR). The whole point of this lib is to save developers' fingers from pointlessly typing the same thing again and again :+1:

**Comment by NullVoxPopuli** [comment]
I think I may be doing something wrong.

I have this function that I use for all my models:

```js
export function buildRest(model, path) {
  const withAuthentication = () => {
    console.log(getToken());

    return {
      headers: {
        ['Authorization']: `Bearer ${getToken()}`
      }
    }
  };

  return {
    list: (params = {}) => fetchCollection(
      model, path, params, withAuthentication()
    ),

    get: ({id, ...params}) => fetchRecord(
      model, id, `${path}/${id}`, params, withAuthentication()
    ),

    create: (data, params = {}) => createRecord(
      model, path, data, params, withAuthentication()
    ),

    update: ({id, ...data}, params = {}) => updateRecord(
      model, id, `${path / $id}`, data, params, withAuthentication()
    ),

    destroy: ({id, ...params}) => deleteRecord(
      model, id, `${path}/${id}`, params, withAuthentication()
    )
  };
}

```

the console.log correctly outputs the token to the console, but in the network tab of chrome's inspector, there is no Authorization header.

I _can_ correctly set headers when I initialize the api client when making the call to `crudSaga`, but, I need per-request headers, because, in an SPA, logging out / re-logging in can happen at any time.

**Comment by devvmh** [comment]
Hmm it looks like you're passing the header to ApiClient correctly.

You might need to add a fetch config `credentials: include` (not in the headers array). see https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

If you can't solve it please cut another issue. if you can please post here for posterity :)

**Comment by NullVoxPopuli** [comment]
it actually looks like, I was missing the fetchConfig key:

```js
  const withAuthentication = () => {
    console.log(getToken());

    return {
      fetchConfig: {
        headers: {
          ['Authorization']: `Bearer ${getToken()}`
        }
      }
    }
  };
```

this works :-)
found out I needed fetchConfig via one of the dependent repos
