### ISSUE TITLE
How to use a filter with fetchCollection ?

### ISSUE THREAD

**Issue by chawax** [uniqueway/redux-crud-store#54]
I use fetchCollection to retrieve data from an API but I need to filter the collection before Redux Crud Store put them in the store, ie before FETCH_SUCCESS reducer is called. How can I do that ?

**Comment by devvmh** [comment]
Hi

Interesting question. There's no native support for this in the lib, at least not the way you're describing.

I see three possible ways to accomplish what you're thinking of.

1. Make the filter available on the server side by passing a filter parameter. This will return the filtered collection which will be stored along with the filter parameters. Then pass the same params to your selector, and you'll get the filtered collection.
2. Modify your ApiClient.js. You can copy the api client out of redux-crud-store's source, patch it, and then import the patched version of the ApiClient instead of redux-crud-store's. You can add any logic you like to this, including filtering in some scenarios (e.g. if a certain option is passed)
3. Don't store the filtered records in the store, but make a custom selector that will filter the records for you.

Hopefully one of those methods work. If I've misunderstood, please let me know.

**Comment by devvmh** [comment]
I'm closing this issue; feel free to re-open or open a new issue if you have more questions
