### ISSUE TITLE
Store data from response of a create?

### ISSUE THREAD

**Issue by NullVoxPopuli** [uniqueway/redux-crud-store#67]
I'm doing a POST / creating a record, and the response is the full json document representing the newly created record -- it's not in the redux store -- is there something I need to do to put it there?

thanks!

**Comment by devvmh** [comment]
The byid reducer should be adding it

    case CREATE_SUCCESS:
      return Object.assign({}, state, {
        [action.payload.id]: {
          fetchTime: action.meta.fetchTime,
          error: null,
          record: action.payload
        }
      })

This might tbe the same issue as #64. Otherwise I'll put some thought into using an adapter/parser like you mentioned on the other issue.

I dont have loads of free time to work on this sibce my current job doesn't use react/redux. But I'd love to review a pull request if you have the time :D even a draft or proof of concept

**Comment by NullVoxPopuli** [comment]
It was, turns out I was formatting the json wrong.
